name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install sqlite
      run: |
        apt-get update
        apt-get install -y libsqlite3-dev
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: KEMAL_ENV=test crystal spec -v
